### ISSUE TITLE
visitorLog Data file

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-muntjac#105]
### **Dev Story**
--- 
As a user i should see a json/data file that has been imported into firebase that contains/holds the data of all activity and spending by all visitors. When the buy button is clicked and all visitors buy something at random ( #94 ) what they buy will be pushed to this data file with the visitor, what they bought, and how much it cost.

### **AC**
---
**When** the dev views the code they should see a json file name visitorLog
**When** the dev views this data it should have properties for the visitors name, activity, and expenditure)
**Then** the dev should see on firebase where the json file has been imported
**Finally** any new purchase of a ride/vendor ( #94 ) will push that data from each visitor to this file

### **To Do**
---
- [x] Create a new json file and name is visitorLog
- [x] Add base data to the file(name, activity, and expenditure)
- [x] Import the file into firebase

### **Base Data**
---

```
{

       "visitorLog1": {
          "visitor": "",
           "activity": "",
           "expenditure": (this will be an integer)
    }

}
```

### **ERD**
---
![image](https://user-images.githubusercontent.com/62913995/88599807-4b63df00-d032-11ea-9fa6-95a413faec8f.png)

**Comment by medlenmage** [comment]
@luketlancaster visitorLog. i think this is the jist of what you were saying right?

**Comment by luketlancaster** [comment]
how are you going to find which visitor the items in the log are for?

**Comment by medlenmage** [comment]
i didn't know i was putting that in this card? i was thinking this was just for the initial setup data.

**Comment by luketlancaster** [comment]
currently the way that you have this data setup there's no way to tell which visitor has which which logs...where is that data stored? Where's the relationship? How are you going to find which visitor the items in the log are for?

**Comment by luketlancaster** [comment]
is this new table in the ERD?

**Comment by medlenmage** [comment]
ok just updated the erd for it and added the table for this. i'll rework this card a little later on today
