### ISSUE TITLE
Add Staff to Ride

### ISSUE THREAD

**Issue by gwynnemeeks** [nss-evening-cohort-12/nutshell-muntjac#91]
### **User Story**
As a user, I should be able to assign a Staff member to a Ride (#77 )
---
As a user, when signed in I should be able to visit the staff member page and see a list of staff members. I should be able to click a button that populates a form with radio buttons that allow you to select a single staff member and assign them to that ride.

### **AC**
--- 
**When** the user is signed in and goes to the staff page they should see a list of staff members.
**There** should be a button on each staff member that populates a form with radio buttons with each ride name

### **To Do**
--- 
- [x] Create a component named addStaffRide
- [x] Create a new file called addStaffRide.js
- [x] Create a function that builds a form that will populate from the click of a button
- [x] Create multiple radio buttons on the form one for each ride
- [x] Must be complete before starting issue #108

### **MoqUp**

![image](https://user-images.githubusercontent.com/63276406/88348415-ef881600-cd12-11ea-8154-ab2451721601.png)

**Comment by luketlancaster** [comment]
what kind of axios requests do you see yourself needing for this?
