### ISSUE TITLE
2 Staff = 1 Ride

### ISSUE THREAD

**Issue by gwynnemeeks** [nss-evening-cohort-12/nutshell-muntjac#93]
### **User Story**
---
As a user when i am signed in and go to the rides page i should see a list of rides. When i look at the rides there should be a icon that symbolizes whether the ride is running or not. One symbol is a thumbs up indicating that the ride is staffed and ready to go the other is a wrench indicating that the ride is insufficiently staffed. A banner at the top of the page should alert me to any unstaffed rides.

### **AC**
---
**When** a user visits the riders page they should see a list of rides
**Then** each ride should have one of two icons a green thumbs up or a wrench as well as a banner of any items with wrenches
**When** the banner button is clicked it should direct the user to the staff page to assign a staff member to the ride
**When** the two employees are assigned the wrench should disappear and a green thumbs up should appear indicating its running

### **To Do**
--- 

- [x] #91 
- [x] Generate the number of staff property for ride based on how many staff members assigned (array length)
- [x] isOperational ride property should check to see how many staff members are working a ride, evaluate to true or false, and display the appropriate icon
- [x] Create a function that when the banner button is clicked it prints the staff page cards

### **Dev Notes**
---
As of most recent commit, staff number is a property the user enters, as #91 is still in the works. However, the isOperational property is evaluating correctly based on the integer provided.

**Comment by luketlancaster** [comment]
wireframes?

**Comment by atphy** [comment]
> wireframes?

ticket edited to use only existing page elements

**Comment by luketlancaster** [comment]
how do I know which staff are assigned to which rides? Can staff be assigned to > 1 ride at a time? Sorry if this is in another ticket somewhere and I missed it/forgot...

**Comment by atphy** [comment]
> how do I know which staff are assigned to which rides? Can staff be assigned to > 1 ride at a time? Sorry if this is in another ticket somewhere and I missed it/forgot...

staff can only be assigned to one ride/vendor at a time. this is implied in the ERD and the relevant issues for adding staff to ride/vendors but maybe not outright stated. The staff member's assignment will be on their own card, just a new line of text on there.
